# Generated by Django 3.0.2 on 2020-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200127_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, default='Django.jpg', upload_to='episode-images'),
        ),
    ]
