# Generated by Django 3.0.3 on 2020-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_episode_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podcast-images'),
        ),
    ]
