# Generated by Django 3.0.3 on 2020-04-08 10:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200407_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='actual_file',
            field=models.FileField(blank=True, null=True, upload_to='podcast-images', validators=[blog.models.validate_file_extension]),
        ),
    ]
