# Generated by Django 3.0.3 on 2020-04-08 10:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_podcast_actual_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='actual_file',
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to='files', validators=[blog.models.validate_file_extension]),
        ),
    ]
