# Generated by Django 3.0.3 on 2020-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200408_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='downloads',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='downloads',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, default='Django.jpg', null=True, upload_to='episode-images'),
        ),
    ]
