# Generated by Django 3.0.2 on 2020-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200207_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to='product-images/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
