# Generated by Django 3.0.2 on 2020-02-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200212_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
