# Generated by Django 3.0.2 on 2020-02-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no-image.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
