# Generated by Django 3.0.2 on 2020-02-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
