# Generated by Django 3.0.3 on 2020-02-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200218_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
